/* eslint-disable */
// 由 scripts/gen-char-pages.mjs 自动生成，请勿手动修改
import type { PressTheme } from 'valaxy-theme-press'

export const sidebar: PressTheme.SidebarEntry[] = [
  {
    text: "自建角色",
    link: "/zijian/",
    collapsed: false,
    items: [
    { text: "猫奈（GitHub娘）-CatNai", link: "/zijian/CatNai/", collapsed: false, items: [{ text: '更新日志', link: "/zijian/CatNai/changelog" }] },
    { text: "苏沐曦-Su Muxi", link: "/zijian/Su-Muxi/", collapsed: false, items: [{ text: '更新日志', link: "/zijian/Su-Muxi/changelog" }] },
    ],
  },
  {
    text: "二创角色",
    link: "/erchuang/",
    collapsed: false,
    items: [
    { text: "艾莲-Ellen", link: "/erchuang/Ellen/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Ellen/changelog" }] },
    { text: "爱弥斯-Amis", link: "/erchuang/Amis/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Amis/changelog" }] },
    { text: "爱芮-Airi", link: "/erchuang/Airi/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Airi/changelog" }] },
    { text: "八重神子-Yae Miko", link: "/erchuang/Yae-Miko/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Yae-Miko/changelog" }] },
    { text: "白钰袖-Bai Yuxiu", link: "/erchuang/Bai-Yuxiu/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Bai-Yuxiu/changelog" }] },
    { text: "博士「多托雷」-Dottore", link: "/erchuang/Dottore/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Dottore/changelog" }] },
    { text: "布洛妮娅-Bronya", link: "/erchuang/Bronya/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Bronya/changelog" }] },
    { text: "陈千语-Chen Qianyu", link: "/erchuang/Chen-Qianyu/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Chen-Qianyu/changelog" }] },
    { text: "达妮娅-Daniya", link: "/erchuang/Daniya/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Daniya/changelog" }] },
    { text: "珐露珊-Faruzan", link: "/erchuang/Faruzan/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Faruzan/changelog" }] },
    { text: "菲比-Phoebe", link: "/erchuang/Phoebe/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Phoebe/changelog" }] },
    { text: "芙莉莲-Frieren", link: "/erchuang/Frieren/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Frieren/changelog" }] },
    { text: "芙宁娜-Furina", link: "/erchuang/Furina/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Furina/changelog" }] },
    { text: "格蕾修-Griseo", link: "/erchuang/Griseo/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Griseo/changelog" }] },
    { text: "黑塔-Herta", link: "/erchuang/Herta/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Herta/changelog" }] },
    { text: "胡桃-Hu Tao", link: "/erchuang/Hu-Tao/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Hu-Tao/changelog" }] },
    { text: "花火-Sparkle", link: "/erchuang/Sparkle/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Sparkle/changelog" }] },
    { text: "黄豆粉-Kinako", link: "/erchuang/Kinako/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Kinako/changelog" }] },
    { text: "橘福福-Jufufu", link: "/erchuang/Jufufu/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Jufufu/changelog" }] },
    { text: "刻晴-Keqing", link: "/erchuang/Keqing/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Keqing/changelog" }] },
    { text: "流萤-Firefly", link: "/erchuang/Firefly/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Firefly/changelog" }] },
    { text: "琉音-Rune", link: "/erchuang/Rune/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Rune/changelog" }] },
    { text: "洛茜-Rosie", link: "/erchuang/Rosie/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Rosie/changelog" }] },
    { text: "玛拉妮-Mualani", link: "/erchuang/Mualani/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Mualani/changelog" }] },
    { text: "木偶「桑多涅」-Sandrone", link: "/erchuang/Sandrone/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Sandrone/changelog" }] },
    { text: "纳西妲-Nahida", link: "/erchuang/Nahida/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Nahida/changelog" }] },
    { text: "南宫羽-Nangong Yu", link: "/erchuang/Nangong-Yu/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Nangong-Yu/changelog" }] },
    { text: "佩丽卡-Perica", link: "/erchuang/Perica/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Perica/changelog" }] },
    { text: "绮良良-Kirara", link: "/erchuang/Kirara/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Kirara/changelog" }] },
    { text: "千夏-Chinatsu", link: "/erchuang/Chinatsu/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Chinatsu/changelog" }] },
    { text: "茜特菈莉-Citlali", link: "/erchuang/Citlali/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Citlali/changelog" }] },
    { text: "青衣-Qingyi", link: "/erchuang/Qingyi/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Qingyi/changelog" }] },
    { text: "阮 • 梅-Ruan Mei", link: "/erchuang/Ruan-Mei/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Ruan-Mei/changelog" }] },
    { text: "少女「哥伦比娅」-Columbina", link: "/erchuang/Columbina/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Columbina/changelog" }] },
    { text: "神里绫华-Kamisato Ayaka", link: "/erchuang/Kamisato-Ayaka/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Kamisato-Ayaka/changelog" }] },
    { text: "丝柯克-Skirk", link: "/erchuang/Skirk/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Skirk/changelog" }] },
    { text: "汤汤-Tangtang", link: "/erchuang/Tangtang/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Tangtang/changelog" }] },
    { text: "薇薇安-Vivian", link: "/erchuang/Vivian/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Vivian/changelog" }] },
    { text: "昔涟-Xilian", link: "/erchuang/Xilian/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Xilian/changelog" }] },
    { text: "闲云-Xianyun", link: "/erchuang/Xianyun/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Xianyun/changelog" }] },
    { text: "霄宫-Yoimiya", link: "/erchuang/Yoimiya/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Yoimiya/changelog" }] },
    { text: "星见雅-Hoshimi Miyabi", link: "/erchuang/Hoshimi-Miyabi/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Hoshimi-Miyabi/changelog" }] },
    { text: "叶瞬光-Ye Shunguang", link: "/erchuang/Ye-Shunguang/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Ye-Shunguang/changelog" }] },
    { text: "夜兰-Yelan", link: "/erchuang/Yelan/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Yelan/changelog" }] },
    { text: "伊涅芙-Yiniefu", link: "/erchuang/Yiniefu/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Yiniefu/changelog" }] },
    { text: "银狼-Silver Wolf", link: "/erchuang/Silver-Wolf/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Silver-Wolf/changelog" }] },
    { text: "长夜月-Changye Yue", link: "/erchuang/Changye-Yue/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Changye-Yue/changelog" }] },
    { text: "照-Zhao", link: "/erchuang/Zhao/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Zhao/changelog" }] },
    { text: "知更鸟-Robin", link: "/erchuang/Robin/", collapsed: true, items: [{ text: '更新日志', link: "/erchuang/Robin/changelog" }] },
    ],
  },
]
